version: "3.8"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - SAP_COMPANY_ID=${SAP_COMPANY_ID}
      - SAP_AGENCY_ID=${SAP_AGENCY_ID}
      - SAP_EMAIL=${SAP_EMAIL}
      - SAP_PASSWORD=${SAP_PASSWORD}
    shm_size: '2gb'  # Chrome needs this
